[2023-06-27T09:14:12.329+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select permission to 509
[2023-06-27T09:14:12.330+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select'
[2023-06-27T09:14:12.357+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select permission to 509
[2023-06-27T09:14:12.358+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select'
[2023-06-27T09:14:12.523+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Loop.create_select manual__2023-06-27T09:14:11.133710+00:00 [queued]>
[2023-06-27T09:14:12.532+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Loop.create_select manual__2023-06-27T09:14:11.133710+00:00 [queued]>
[2023-06-27T09:14:12.533+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T09:14:12.549+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_select> on 2023-06-27 09:14:11.133710+00:00
[2023-06-27T09:14:12.554+0000] {standard_task_runner.py:57} INFO - Started process 12870 to run task
[2023-06-27T09:14:12.559+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Loop', 'create_select', 'manual__2023-06-27T09:14:11.133710+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdbxu46b3']
[2023-06-27T09:14:12.561+0000] {standard_task_runner.py:85} INFO - Job 205: Subtask create_select
[2023-06-27T09:14:12.611+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select permission to 509
[2023-06-27T09:14:12.612+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-27T09:14:11.133710+00:00/task_id=create_select'
[2023-06-27T09:14:12.614+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Loop.create_select manual__2023-06-27T09:14:11.133710+00:00 [running]> on host 4d37da440d5c
[2023-06-27T09:14:12.736+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Loop' AIRFLOW_CTX_TASK_ID='create_select' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T09:14:11.133710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T09:14:11.133710+00:00'
[2023-06-27T09:14:12.738+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-27T09:14:12.739+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt run --model select']
[2023-06-27T09:14:12.749+0000] {subprocess.py:86} INFO - Output:
[2023-06-27T09:14:15.501+0000] {subprocess.py:93} INFO - [0m09:14:15  Running with dbt=1.5.1
[2023-06-27T09:14:22.554+0000] {subprocess.py:93} INFO - [0m09:14:22  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-27T09:14:22.555+0000] {subprocess.py:93} INFO - There are 2 unused configuration paths:
[2023-06-27T09:14:22.555+0000] {subprocess.py:93} INFO - - models.badge_5.create_stage
[2023-06-27T09:14:22.556+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day
[2023-06-27T09:14:22.624+0000] {subprocess.py:93} INFO - [0m09:14:22  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 455 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-27T09:14:22.627+0000] {subprocess.py:93} INFO - [0m09:14:22
[2023-06-27T09:14:23.873+0000] {subprocess.py:93} INFO - [0m09:14:23  Concurrency: 200 threads (target='dev')
[2023-06-27T09:14:23.874+0000] {subprocess.py:93} INFO - [0m09:14:23
[2023-06-27T09:14:23.919+0000] {subprocess.py:93} INFO - [0m09:14:23  1 of 1 START sql view model ***.select ..................................... [RUN]
[2023-06-27T09:14:24.487+0000] {subprocess.py:93} INFO - [0m09:14:24  1 of 1 ERROR creating sql view model ***.select ............................ [[31mERROR[0m in 0.57s]
[2023-06-27T09:14:24.541+0000] {subprocess.py:93} INFO - [0m09:14:24
[2023-06-27T09:14:24.543+0000] {subprocess.py:93} INFO - [0m09:14:24  Finished running 1 view model in 0 hours 0 minutes and 1.91 seconds (1.91s).
[2023-06-27T09:14:24.602+0000] {subprocess.py:93} INFO - [0m09:14:24
[2023-06-27T09:14:24.603+0000] {subprocess.py:93} INFO - [0m09:14:24  [31mCompleted with 1 error and 0 warnings:[0m
[2023-06-27T09:14:24.604+0000] {subprocess.py:93} INFO - [0m09:14:24
[2023-06-27T09:14:24.605+0000] {subprocess.py:93} INFO - [0m09:14:24  [33mDatabase Error in model select (models/select/select.sql)[0m
[2023-06-27T09:14:24.606+0000] {subprocess.py:93} INFO - [0m09:14:24    001003 (42000): SQL compilation error:
[2023-06-27T09:14:24.607+0000] {subprocess.py:93} INFO - [0m09:14:24    syntax error line 1 at position 43 unexpected '.'.
[2023-06-27T09:14:24.608+0000] {subprocess.py:93} INFO - [0m09:14:24    compiled Code at target/run/badge_5/models/select/select.sql
[2023-06-27T09:14:24.609+0000] {subprocess.py:93} INFO - [0m09:14:24
[2023-06-27T09:14:24.611+0000] {subprocess.py:93} INFO - [0m09:14:24  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-06-27T09:14:25.232+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-27T09:14:25.244+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-27T09:14:25.248+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=2_Test_Badge_5_Loop, task_id=create_select, execution_date=20230627T091411, start_date=20230627T091412, end_date=20230627T091425
[2023-06-27T09:14:25.263+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 205 for task create_select (Bash command failed. The command returned a non-zero exit code 1.; 12870)
[2023-06-27T09:14:25.292+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-27T09:14:25.306+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
