[2023-06-23T15:05:48.200+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage permission to 509
[2023-06-23T15:05:48.201+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage'
[2023-06-23T15:05:48.278+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage permission to 509
[2023-06-23T15:05:48.279+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage'
[2023-06-23T15:05:48.311+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5.test_create_stage manual__2023-06-23T15:05:45.118307+00:00 [queued]>
[2023-06-23T15:05:48.320+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5.test_create_stage manual__2023-06-23T15:05:45.118307+00:00 [queued]>
[2023-06-23T15:05:48.321+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-23T15:05:48.335+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): test_create_stage> on 2023-06-23 15:05:45.118307+00:00
[2023-06-23T15:05:48.344+0000] {standard_task_runner.py:57} INFO - Started process 70 to run task
[2023-06-23T15:05:48.348+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5', 'test_create_stage', 'manual__2023-06-23T15:05:45.118307+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmplmdesc2m']
[2023-06-23T15:05:48.350+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask test_create_stage
[2023-06-23T15:05:48.392+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage permission to 509
[2023-06-23T15:05:48.393+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5/run_id=manual__2023-06-23T15:05:45.118307+00:00/task_id=test_create_stage'
[2023-06-23T15:05:48.396+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5.test_create_stage manual__2023-06-23T15:05:45.118307+00:00 [running]> on host 9b03f6d5dc98
[2023-06-23T15:05:48.514+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5' AIRFLOW_CTX_TASK_ID='test_create_stage' AIRFLOW_CTX_EXECUTION_DATE='2023-06-23T15:05:45.118307+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-23T15:05:45.118307+00:00'
[2023-06-23T15:05:48.516+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-23T15:05:48.517+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt run --model ed_pipeline_logs']
[2023-06-23T15:05:48.589+0000] {subprocess.py:86} INFO - Output:
[2023-06-23T15:05:51.746+0000] {subprocess.py:93} INFO - [0m15:05:51  Running with dbt=1.5.1
[2023-06-23T15:05:53.004+0000] {subprocess.py:93} INFO - [0m15:05:53  Unable to do partial parsing because profile has changed
[2023-06-23T15:05:59.965+0000] {subprocess.py:93} INFO - [0m15:05:59  Encountered an error:
[2023-06-23T15:05:59.966+0000] {subprocess.py:93} INFO - Compilation Error
[2023-06-23T15:05:59.967+0000] {subprocess.py:93} INFO -   dbt found two models with the name "ed_pipeline_logs".
[2023-06-23T15:05:59.968+0000] {subprocess.py:93} INFO - 
[2023-06-23T15:05:59.968+0000] {subprocess.py:93} INFO -   Since these resources have the same name, dbt will be unable to find the correct resource
[2023-06-23T15:05:59.969+0000] {subprocess.py:93} INFO -   when looking for ref("ed_pipeline_logs").
[2023-06-23T15:05:59.969+0000] {subprocess.py:93} INFO - 
[2023-06-23T15:05:59.970+0000] {subprocess.py:93} INFO -   To fix this, change the name of one of these resources:
[2023-06-23T15:05:59.970+0000] {subprocess.py:93} INFO -   - model.badge_5.ed_pipeline_logs (models/ed_pipeline_logs/target/compiled/badge_5/models/ed_pipeline_logs/ed_pipeline_logs.sql)
[2023-06-23T15:05:59.971+0000] {subprocess.py:93} INFO -   - model.badge_5.ed_pipeline_logs (models/ed_pipeline_logs/ed_pipeline_logs.sql)
[2023-06-23T15:06:00.534+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-23T15:06:00.544+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-23T15:06:00.548+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=2_Test_Badge_5, task_id=test_create_stage, execution_date=20230623T150545, start_date=20230623T150548, end_date=20230623T150600
[2023-06-23T15:06:00.561+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 36 for task test_create_stage (Bash command failed. The command returned a non-zero exit code 2.; 70)
[2023-06-23T15:06:00.698+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-23T15:06:00.716+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
