[2023-06-28T14:10:06.753+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task permission to 509
[2023-06-28T14:10:06.754+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task'
[2023-06-28T14:10:06.786+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task permission to 509
[2023-06-28T14:10:06.787+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task'
[2023-06-28T14:10:06.825+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Loop.snowflake_sensor_task manual__2023-06-28T14:10:02.830923+00:00 [queued]>
[2023-06-28T14:10:06.840+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Loop.snowflake_sensor_task manual__2023-06-28T14:10:02.830923+00:00 [queued]>
[2023-06-28T14:10:06.841+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-28T14:10:06.857+0000] {taskinstance.py:1327} INFO - Executing <Task(SnowflakeStreamSensor): snowflake_sensor_task> on 2023-06-28 14:10:02.830923+00:00
[2023-06-28T14:10:06.862+0000] {standard_task_runner.py:57} INFO - Started process 231 to run task
[2023-06-28T14:10:06.866+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Loop', 'snowflake_sensor_task', 'manual__2023-06-28T14:10:02.830923+00:00', '--job-id', '521', '--raw', '--subdir', 'DAGS_FOLDER/test_loop.py', '--cfg-path', '/tmp/tmp21jndyqj']
[2023-06-28T14:10:06.867+0000] {standard_task_runner.py:85} INFO - Job 521: Subtask snowflake_sensor_task
[2023-06-28T14:10:06.914+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task permission to 509
[2023-06-28T14:10:06.915+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=manual__2023-06-28T14:10:02.830923+00:00/task_id=snowflake_sensor_task'
[2023-06-28T14:10:06.918+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Loop.snowflake_sensor_task manual__2023-06-28T14:10:02.830923+00:00 [running]> on host 20abcf34034c
[2023-06-28T14:10:07.006+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Loop' AIRFLOW_CTX_TASK_ID='snowflake_sensor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-28T14:10:02.830923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-28T14:10:02.830923+00:00'
[2023-06-28T14:10:07.106+0000] {base.py:73} INFO - Using connection ID 'snowflake_connection' for task execution.
[2023-06-28T14:10:07.110+0000] {connection.py:265} INFO - Snowflake Connector for Python Version: 2.4.5, Python Version: 3.7.16, Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-debian-11.7
[2023-06-28T14:10:07.111+0000] {connection.py:869} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-06-28T14:10:07.112+0000] {connection.py:886} INFO - Setting use_openssl_only mode to False
[2023-06-28T14:10:07.753+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/snowflake_sensor.py", line 36, in execute
    result = snowflake_conn.execute(query)
AttributeError: 'SnowflakeConnection' object has no attribute 'execute'
[2023-06-28T14:10:07.766+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=2_Test_Badge_5_Loop, task_id=snowflake_sensor_task, execution_date=20230628T141002, start_date=20230628T141006, end_date=20230628T141007
[2023-06-28T14:10:07.782+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 521 for task snowflake_sensor_task ('SnowflakeConnection' object has no attribute 'execute'; 231)
[2023-06-28T14:10:07.800+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-28T14:10:07.826+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
